version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
      - image: circleci/mongo:3
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: tests
          command: npm test
      - start:
          name: run the app
          command: npm start
