version: 2
jobs:
  build:
    working_directory: ~/node-express-di
    docker:
      - image: circleci/node:8
      - image: circleci/mongo:3
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: tests
          command: npm test
      - run:
          name: docker build image
          command: docker build -t node-express:$CIRCLE_BRANCH .


